AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api
      Handler: get-data.handler
      Runtime: nodejs18.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get-data
            Method: GET
      Environment:
        Variables:
          STAGE: prod
